input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 3; index++) {
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, 1)
        basic.pause(200)
        sprite.delete()
        basic.pause(100)
        sprite = game.createSprite(4, 4)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, -1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.Y, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, 1)
        basic.pause(200)
        sprite.change(LedSpriteProperty.X, 1)
        basic.pause(100)
    }
})
let sprite: game.LedSprite = null
sprite = game.createSprite(3, 3)
basic.forever(function () {
	
})
